### ISSUE TITLE
Multi Support Not Working?

### ISSUE THREAD

**Issue by SENTINELITE** [emorydunn/StreamDeckPlugin#11]
Hey there! 

For a few months now, my plugin hasn't been able to use Multi-Action support. I dumbed this down to an error on my side, but after extreme debugging, I couldn't get it to work. 

I went ahead & forked the latest, current branch of the Counter plugin, & can't seem to get any logs or any of the actions to work with-in a Multi-Action. 

Could you take a look & let me know if I'm missing something, or if this is indeed a bug? 

Thanks!

**Comment by emorydunn** [comment]
Multi-actions should work, and are enabled by default, but I don't recall if I've actually tested them, so I'll take a look. 

Which version of the API are you using?

**Comment by SENTINELITE** [comment]
Not sure if you're talking about the StreamDeck version? If so, 5.0+. Also tested on the latest 5.3 Beta release. 

As for this library, I forked the current version back in mid December, with some custom changes, for logging & learning the package. 

I'm not getting any logs with the latest release. I've went ahead & attached some console logs from the December fork, as Multi-Action semi-worked...

I asked around & it appears that actions inside the Multi-Action shouldn't have coordinates?  I went ahead & attached Elgato's Manifest.json, located under `~/Library/Application Support/com.elgato.StreamDeck/ProfilesV2`, & then one of your profiles. 

Let me know if there's anything else you need!

[ConsoleLog.txt](https://github.com/emorydunn/StreamDeckPlugin/files/8626429/ConsoleLog.txt)
[Exmaple_Manifest.txt](https://github.com/emorydunn/StreamDeckPlugin/files/8626467/Exmaple_Manifest.txt)

**Comment by SENTINELITE** [comment]
Hey, @emorydunn! 

Just wanted to check in & see if you were able to dig into this. Again, if you need anything else, I can provide more info! 

Thanks!

**Comment by emorydunn** [comment]
Hi @SENTINELITE Thank you for your patience! I finally found to time to do some Stream Deck updates (both the library and my own plugin) and it looks like you were right about the coordinates, marking them as optional seems to have solved the issue. 

I just pushed an update to the `main` branch which should get multi-actions working. Let me know if it does the trick.

**Comment by SENTINELITE** [comment]
Hey, @emorydunn.

That's done the trick! Thanks for taking a look! 😀
