### ISSUE TITLE
missing events

### ISSUE THREAD

**Issue by justme-1968** [emorydunn/StreamDeckPlugin#24]
would you mind adding some missing events/messages:

- didReceiveDeepLink (receiving)
- openURL (sending)

also: i think it would be nice if there was a way to handle unknown events maybe by registering a handler for a specific unknown event or a general handler that will receive everything that is not known.

and probably the same for sending

**Comment by emorydunn** [comment]
Not sure how I missed those two events during the last update, I'll add them in. 

Implementing an unknown event handler is a good idea, I should be able to add a method to the main plugin protocol to handle them, with a default implementation that just logs the event as unknown.

**Comment by emorydunn** [comment]
I've added `Plugin.didReceiveDeepLink(_:)` and associated event routing as well as `Action.openURL(_:)` to open URLs from an action instance. 

There's also a new `Plugin.eventError(_:data:)` to handle errors parsing events. This will be called for unknown events where the data can be manually parsed as needed.
